services:
  mc-server:
    build: .
    container_name: minecraft-server-container
    ports:
      - "8888:25565"
    volumes:
      - ./mc-server:/app/server            
    restart: unless-stopped
    stdin_open: true
    tty: true
volumes:
  mc-server:   
